name: CI Pipeline

on:
  push:
    branches:
      - main  # Déclenche le pipeline lorsque des modifications sont poussées sur la branche principale
  pull_request:
    branches:
      - main  # Déclenche le pipeline pour les pull requests sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar  # Ajoutez ici le chemin des fichiers à archiver, par exemple le jar de votre application
